name = "finishonethingtoday"
main = "src/index.js"
compatibility_date = "2024-12-06"

[[d1_databases]]
binding = "DB"
database_name = "finishonething_db"
database_id = "ad76b5c9-01a6-4abd-ba32-aeb783a6a067" 

# If you have a custom domain set up, something like:
[vars]
# environment variables if needed

# [route]
# routes = ["finishonethingtoday.com/*"]

