INSERT INTO quotes (quote_text, author) VALUES
('The journey of a thousand miles begins with one step.', 'Lao Tzu'),
('Focus on progress, not perfection.', 'Bill Phillips'),
('Small steps every day add up to big results.', 'Satya Nani'),
('Today''s actions shape tomorrow''s achievements.', 'Unknown'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe'),
('The only way to do great work is to love what you do.', 'Steve Jobs'),
('Your future self will thank you for what you do today.', 'Unknown'),
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
('The only limit to our realization of tomorrow is our doubts of today.', 'Franklin D. Roosevelt'),
('Act as if what you do makes a difference. It does.', 'William James'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson'),
('The future depends on what you do today.', 'Mahatma Gandhi'),
('You don''t have to be great to start, but you have to start to be great.', 'Zig Ziglar'),
('Small deeds done are better than great deeds planned.', 'Peter Marshall'),
('Action is the foundational key to all success.', 'Pablo Picasso'),
('The only impossible journey is the one you never begin.', 'Tony Robbins'),
('Inaction breeds doubt and fear. Action breeds confidence and courage.', 'Dale Carnegie'),
('You are what you do, not what you say you''ll do.', 'Carl Jung'),
('Dreams don''t work unless you take action.', 'Roy T. Bennett'),
('The mountains are calling and I must go.', 'John Muir'),
('It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena.', 'Theodore Roosevelt'); 