DROP TABLE IF EXISTS quotes;
DROP TABLE IF EXISTS visitors;

CREATE TABLE IF NOT EXISTS quotes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quote_text TEXT NOT NULL,
  author TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS visitors (
  id INTEGER PRIMARY KEY,
  count INTEGER DEFAULT 0
);
INSERT OR REPLACE INTO visitors (id, count) VALUES (1, 0);

